import type { Metadata } from "next";
import "@/font/pretendard/pretendard-subset.css";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export const metadata: Metadata = {
  title: "꼬순내",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="mx-auto h-full max-w-[375px] bg-blue-500">
        <div className="relative h-full bg-white">{children}</div>
      </body>
    </html>
  );
}
